name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: |
            <!--START_SECTION:waka-->
            [![WakaTime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Quisui&theme=vue&langs_count=10)](https://wakatime.com/@Quisui)
            <!--END_SECTION:waka-->

            <!--START_SECTION:top_lang-->
            [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Quisui&hide=css,html&langs_count=6&theme=vue)](https://github.com/Quisui)
            <!--END_SECTION:top_lang-->

            <!--START_SECTION:github_stats-->
            [![Quisui's github stats](https://github-readme-stats.vercel.app/api?username=Quisui&show_icons=true&theme=vue)](https://github.com/Quisui)
            <!--END_SECTION:github_stats-->

            <!--START_SECTION:waka-->
            ```text
            ${WAKATIME_PERIOD_TEXT}
            ```
            <!--END_SECTION:waka-->
